added startup script, starting chain in background and distributing i…
leapdao/nervos pull request #30
Opened 2020-09-09 15:21 UTC by Clearwood

Adding a startup script, starting the Ethermint chain in the background and distributing initial values.

2020-09-10 12:13 UTC, johannbarbie requested changes
great work to a difficult task.

a few things have not been addressed, for example:
- reading out bridge balance on parent chain
- validators need to be entered into genesis file of child chain

consider forking out into bounty similar to documentation. 

requesting cleanup (remove sleep, double declaration of variables, missing comments) of script, then ready to go

2020-09-10 12:13 UTC, johannbarbie commented on packages/childchain/transactions.js
> +(async () => {
why not make this part of truffle deploy?

2020-09-10 12:13 UTC, johannbarbie commented on packages/childchain/childchain.sh
> +ethermintd add-genesis-account $(ethermintcli keys show $KEY -a) 10000000000000001000000000000aphoton,1000000000000000000stake
- instead of 10000000000000001000000000000, mint `0xff..30xff..ff` (max supply) to deployment account. 
- also give stake to other 3 validators here

2020-09-10 12:13 UTC, johannbarbie commented on packages/childchain/childchain.sh
> +pk=$(ethermintcli keys unsafe-export-eth-key $KEY)
avoid using validator key for deployment account

2020-09-10 12:13 UTC, johannbarbie commented on packages/childchain/childchain.sh
> +coproc ethermintcli rest-server --laddr "tcp://localhost:8545" --unlock-key $KEY --chain-id $CHAINID --trace > /dev/null
good job figuring out `coproc`

2020-09-10 12:13 UTC, johannbarbie commented on packages/childchain/childchain.sh
> +VALIDATORS=("0xf3beac30c498d9e26865f34fcaa57dbb935b0d74" "0xe10f3d125e5f4c753a6456fc37123cf17c6900f2" "0xc3ccb3902a164b83663947aff0284c6624f3fbf2" "0x82e8c6cf42c8d1ff9594b17a3f50e94a12cc860f")
load addresses from config here.

2020-09-10 12:13 UTC, johannbarbie commented on packages/childchain/contracts/bridge.sol
>  contract Bridge {
you could add a function `circulatingSupply()` here, and then calculate `0xff..ff - address(this).balance`

2020-09-10 12:13 UTC, johannbarbie commented on packages/childchain/transactions.js
> +    await web3.eth.sendTransaction({
CKB supply is ever growing through secondary issuance, better use max supply than specific cutoff.

2020-09-10 12:13 UTC, johannbarbie commented on packages/childchain/config.json
> +  "validatorStake": "20000000000000000000000000"
in another PR all values in this file should be read from CKB.

2020-09-10 12:13 UTC, johannbarbie commented on packages/childchain/childchain.sh
> +coproc ethermintcli rest-server --laddr "tcp://localhost:8545" --unlock-key $KEY --chain-id $CHAINID --trace > /dev/null
leave a comment for every line to explain what it does.

2020-09-10 13:33 UTC, johannbarbie commented on packages/childchain/childchain.sh
>  ethermintd gentx --name $KEY --keyring-backend test
this needs to happen for every address in the validator list

2020-09-16 15:59 UTC, Clearwood commented on packages/childchain/childchain.sh
> +sleep 2
yes unfortunately so, I checked the ethermint repo and they even used a 5 second sleep https://github.com/ChainSafe/ethermint/blob/244d83666936fb7ee4b8704bd4a18bb07954487f/scripts/start.sh#L3

2020-09-22 14:25 UTC, Clearwood commented
@johannbarbie addressed changes and changed to single validator setup

2020-09-23 11:51 UTC, Clearwood commented
@johannbarbie added changes

2020-09-25 07:54 UTC, johannbarbie commented on packages/childchain/childchain.sh
> +ALICE_PK="0x278a5de700e29faae8e40e366ec5012b5ec63d36ec77e8a2417154cc1d25383f"
this is not used anywhere?

2020-09-25 07:55 UTC, johannbarbie commented on packages/childchain/childchain.sh
> +ethermintd add-genesis-account $(ethermintcli keys show $KEY -a) 1329227995784915862903807060280344576aphoton
why `16^30` and not `2^256`?

2020-09-25 08:00 UTC, johannbarbie approved these changes
soso, pretty messy still, but bounty size exceeded.
i've forked out the most important next steps into separate issues:
https://github.com/leapdao/nervos/issues/41
https://github.com/leapdao/nervos/issues/42
https://github.com/leapdao/nervos/issues/43
https://github.com/leapdao/nervos/issues/44

@Clearwood would like to see you pick up the above ☝️

2020-10-09 07:26 UTC, merged